name = "estudiantes-tbo-api"
main = "cloudflare/worker.mjs"
compatibility_date = "2026-04-13"

[[d1_databases]]
binding = "DB"
database_name = "estudiantes-tbo"
database_id = "92ffcab8-c001-44fb-ad7a-89c1872c82cf"
preview_database_id = "92ffcab8-c001-44fb-ad7a-89c1872c82cf"
